sudo: required
services:
  - docker

before_install:
  - docker build -t ahinger/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahinger/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-862676832166"
  bucket_path: "docket-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
language: generic
